CREATE TABLE `feedback` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`site_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`page_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`form_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`text` TEXT NOT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`creator_id` INT(10) NOT NULL DEFAULT '0',
	`updated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`updater_id` INT(10) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
ROW_FORMAT=DEFAULT;